execution:
    uuid: 17545531-f132-4761-919b-63e4f7cb46d0
    runtime:
        start: 2020-08-21T11:06:27.477367-07:00
        end: 2020-08-21T11:08:45.603707-07:00
        duration: 2 minutes, 18 seconds, and 126340 microseconds

action:
    type: method
    plugin: !ref 'environment:plugins:demux'
    action: emp_paired
    inputs:
    -   seqs: 3c965d73-a5a6-43cc-a4ad-2121de05fb9b
    parameters:
    -   barcodes: !metadata 'barcodes.tsv'
    -   golay_error_correction: true
    -   rev_comp_barcodes: false
    -   rev_comp_mapping_barcodes: true
    output-name: per_sample_sequences
    citations:
    - !cite 'action|demux:2020.8.0|method:emp_paired|0'
    - !cite 'action|demux:2020.8.0|method:emp_paired|1'

transformers:
    inputs:
        seqs:
        -   from: EMPPairedEndDirFmt
            to: q2_demux._demux:BarcodePairedSequenceFastqIterator
            plugin: !ref 'environment:plugins:demux'
    output:
    -   from: SingleLanePerSamplePairedEndFastqDirFmt
        to: SingleLanePerSamplePairedEndFastqDirFmt

environment:
    platform: macosx-10.9-x86_64
    python: |-
        3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:19:23)
        [GCC Clang 10.0.1 ]
    framework:
        version: 2020.8.0
        website: https://qiime2.org
        citations:
        - !cite 'framework|qiime2:2020.8.0|0'
    plugins:
        demux:
            version: 2020.8.0
            website: https://github.com/qiime2/q2-demux
        types:
            version: 2020.8.0
            website: https://github.com/qiime2/q2-types
    python-packages:
        zipp: 3.1.0
        xopen: 0.9.0
        widgetsnbextension: 3.5.1
        wheel: 0.35.1
        webencodings: 0.5.1
        wcwidth: 0.2.5
        urllib3: 1.25.10
        unifrac: 0.10.0
        tzlocal: '2.1'
        typing-extensions: 3.7.4.2
        traitlets: 4.3.3
        tornado: 6.0.4
        toml: 0.10.1
        threadpoolctl: 2.1.0
        testpath: 0.4.4
        terminado: 0.8.3
        statsmodels: 0.11.1
        sphinxcontrib-serializinghtml: 1.1.4
        sphinxcontrib-qthelp: 1.0.3
        sphinxcontrib-jsmath: 1.0.1
        sphinxcontrib-htmlhelp: 1.0.3
        sphinxcontrib-devhelp: 1.0.2
        sphinxcontrib-bibtex: 1.0.0
        sphinxcontrib-applehelp: 1.0.2
        Sphinx: 3.2.1
        snowballstemmer: 2.0.0
        six: 1.15.0
        setuptools: 49.6.0.post20200814
        sepp: 4.3.10
        Send2Trash: 1.5.0
        seaborn: 0.10.1
        scipy: 1.5.2
        scikit-learn: 0.23.1
        scikit-bio: 0.5.5
        requests: 2.24.0
        qiime2: 2020.8.0
        q2templates: 2020.8.0
        q2doc: 0.0.0
        q2cli: 2020.8.0
        q2-vsearch: 2020.8.0
        q2-types: 2020.8.0
        q2-taxa: 2020.8.0
        q2-sample-classifier: 2020.8.0
        q2-quality-filter: 2020.8.0
        q2-quality-control: 2020.8.0
        q2-phylogeny: 2020.8.0
        q2-metadata: 2020.8.0
        q2-longitudinal: 2020.8.0
        q2-gneiss: 2020.8.0
        q2-fragment-insertion: 2020.8.0
        q2-feature-table: 2020.8.0
        q2-feature-classifier: 2020.8.0
        q2-emperor: 2020.8.0
        q2-diversity: 2020.8.0
        q2-diversity-lib: 2020.8.0
        q2-demux: 2020.8.0
        q2-deblur: 2020.8.0
        q2-dada2: 2020.8.0
        q2-cutadapt: 2020.8.0
        q2-composition: 2020.8.0
        q2-alignment: 2020.8.0
        pyzmq: 19.0.2
        PyYAML: 5.3.1
        pytz: '2020.1'
        python-dateutil: 2.8.1
        pytest: 6.0.1
        PySocks: 1.7.1
        pyrsistent: 0.16.0
        pyparsing: 2.4.7
        pyOpenSSL: 19.1.0
        Pygments: 2.6.1
        pycparser: '2.20'
        pybtex: 0.22.2
        pybtex-docutils: 0.2.2
        py: 1.9.0
        ptyprocess: 0.6.0
        psutil: 5.7.2
        prompt-toolkit: 3.0.6
        prometheus-client: 0.8.0
        pluggy: 0.13.1
        pip: 20.2.2
        Pillow: 7.2.0
        pickleshare: 0.7.5
        pexpect: 4.8.0
        patsy: 0.5.1
        parso: 0.7.1
        pandocfilters: 1.4.2
        pandas: 0.25.3
        packaging: '20.4'
        oset: 0.1.3
        olefile: '0.46'
        numpy: 1.19.1
        notebook: 6.1.3
        nose: 1.3.7
        networkx: '2.4'
        nbformat: 5.0.7
        nbconvert: 5.6.1
        natsort: 7.0.1
        msgpack: 1.0.0
        more-itertools: 8.4.0
        mistune: 0.8.4
        matplotlib: 3.2.2
        MarkupSafe: 1.1.1
        lxml: 4.5.2
        lockfile: 0.12.2
        latexcodec: 2.0.1
        kiwisolver: 1.2.0
        jupyter-core: 4.6.3
        jupyter-client: 6.1.6
        jsonschema: 3.2.0
        joblib: 0.16.0
        Jinja2: 2.11.2
        jedi: 0.17.2
        ipywidgets: 7.5.1
        ipython: 7.16.1
        ipython-genutils: 0.2.0
        ipykernel: 5.3.4
        iniconfig: 1.0.1
        importlib-metadata: 1.7.0
        imagesize: 1.2.0
        ijson: 3.1.1
        idna: '2.10'
        hdmedians: '0.13'
        h5py: 2.10.0
        gneiss: 0.4.6
        future: 0.18.2
        fastcluster: 1.1.26
        entrypoints: '0.3'
        emperor: 1.0.1
        docutils: '0.16'
        dnaio: 0.4.2
        DendroPy: 4.4.0
        defusedxml: 0.6.0
        decorator: 4.4.2
        deblur: 1.1.0
        Cython: 0.29.21
        cycler: 0.10.0
        cutadapt: '2.10'
        cryptography: '3.0'
        click: 7.1.2
        chardet: 3.0.4
        cffi: 1.14.1
        certifi: 2020.6.20
        CacheControl: 0.12.6
        brotlipy: 0.7.0
        bokeh: 2.1.1
        bleach: 3.1.5
        biom-format: 2.1.8
        bibtexparser: 1.1.0
        backports.functools-lru-cache: 1.6.1
        backcall: 0.2.0
        Babel: 2.8.0
        attrs: 20.1.0
        argon2-cffi: 20.1.0
        appnope: 0.1.0
        alabaster: 0.7.12
